- src/widgets/codes-lists/components/codes-lists.jsx
Ticket 313 - Tri des liste de codes du questionnaire
This orders the CodesList alphabetically (by label) on the Dropdown 'Specify the code list'.
> Sort CodesList by alphabetical order

- src/actions/app-state.js
- src/model/transformations/component.js
- src/utils/remote-api.js
> Revert "visualisatio questionnaire"

- src/model/transformations/collected-variable.js
- src/model/transformations/collected-variable.spec.js
- src/model/transformations/response-format-simple.js
- src/model/transformations/response-format-simple.spec.js
- src/model/transformations/response-format-table.js
- src/utils/validation/validation-rules.js
This fixes the issues in 192-FO-Ajouter un format pour les Réponse simple/Durée en heures-centièmes.
> [FIX] Duration Format Hour/Hundredth 

- src/constants/dictionary.js
- src/layout/questionnaire-list/components/questionnaire-list.jsx
- src/layout/questionnaire-list/components/questionnaire-list.spec.js
318FO-Message au chargement de la liste de questionnaires en page d'accueil
This renders a loading message when fetching questionnaires.
> Loading Message when Fetching Questionnaires

- src/forms/validation-rules.js
generation-collectedVariable-collected #361
without loop to go in production
> ticket 312

- src/actions/questionnaire.js
- src/constants/dictionary.js
- src/layout/questionnaire-list/components/questionnaire-list.jsx
- src/layout/questionnaire-list/components/questionnaire.jsx
- src/layout/questionnaire-list/containers/questionnaire-list-container.js
325-Dupliquer un questionnaire
> Duplicate Questionnaire

- src/utils/utils.js
- src/utils/utils.spec.js
- src/widgets/component-new-edit/model/component.js
- src/widgets/component-new-edit/model/control.js
- src/widgets/component-new-edit/model/declaration.js
- src/widgets/component-new-edit/model/response-format-table.js
263 -FO- Retirer la parsing sur les variables avec un seul dollar (générateur DDI)
If the last character in the Variable is a symbol (`'=', '*', '+', '-', '!'`), no $ should be added to the end.
> [FIX] Do not add $ to the Variable if the last character is a symbol

- src/actions/actionComponent.js
- src/constants/dictionary.js
- src/constants/pogues-constants.js
- src/widgets/codes-lists/components/codes-lists-actions.jsx
- src/widgets/codes-lists/constants.js
- src/widgets/codes-lists/utils/actions.js
https://github.com/InseeFr/Pogues/issues/497
Tooltip over code list item actions
> [#497] add codeList tooltip on button

- package.json
- src/layout/questionnaire-list/components/questionnaire-list.jsx
- src/widgets/component-new-edit/components/response-format/simple/simple-date.jsx
- fix date range
- use the new column Name in the endpoint "getQuestionnaires" to remove the call of the endpoint "getQuestionnaire" when adding a questionnaire reference
> Dev fix date range

- src/forms/validation-rules.js
- src/layout/header/header.jsx
- src/model/formToState/component-new-edit/collected-variable.js
- src/model/transformations/response-format-table.js
- src/utils/variables/collected-variables-utils.js
- src/utils/variables/collected-variables-utils.spec.js
Refactor Question validation rules + collected variable initialisation
> Dev check variable evolution in array

- src/model/formToState/component-new-edit/declaration.js
- src/widgets/component-new-edit/components/component-new-edit.jsx
- src/widgets/component-new-edit/components/declarations.jsx
> fix: declaration default modes

- src/actions/metadata.js
- src/utils/codes-lists/__mocks__/get-nomenclatures.json
> feat: add new nomenclatures

- src/widgets/component-new-edit/components/response-format/simple/response-format-simple.jsx
- src/widgets/component-new-edit/components/response-format/table/input-measure.jsx
> fix: missing * in min/max label for number simple question

- src/utils/codes-lists/__mocks__/get-nomenclatures.json
- https://github.com/InseeFr/Pogues/issues/801#issuecomment-2358683196
> chore: add nomenclature

- src/constants/dictionary.jsx
- src/model/transformations/control.jsx
- src/model/transformations/control.spec.jsx
- src/widgets/component-new-edit/components/controls.jsx
- src/widgets/component-new-edit/components/sequence-new-edit.jsx
> Allow checks (Occurrence / Whole) for roundabouts

- src/constants/dictionary.ts
- src/layout/versions/components/VersionDetails.tsx
- src/layout/versions/components/Versions.tsx
- src/widgets/inlineConfirm/component.tsx
- Added description in versions screen
- Confirmation text is bigger
- Load button is yellow
- Changed date/name displayed
> feat: improved versions screen

- next/src/components/legacy/index.tsx
- next/src/routes/questionnaire/$questionnaireId/composition.tsx
- next/src/routes/questionnaire/$questionnaireId/index.tsx
- next/src/routes/questionnaire/$questionnaireId/merge.tsx
- next/src/routes/questionnaire/$questionnaireId/tcm-composition.tsx
do not duplicated Legacy component
> fix: composition and merge

- .github/workflows/ci.yaml
Split release process for next
> ci: fix release for next

- next/package.json
- next/src/api/utils/questionnaires.ts
- next/src/components/createQuestionnaire/CreateQuestionnaire.tsx
- next/src/components/ui/Button.tsx
- next/src/models/questionnaires.ts
- next/src/routes/__root.tsx
- next/src/routes/_auth.tsx
- next/src/routes/_auth/questionnaires/index.tsx
- next/tailwind.config.js
- next/yarn.lock
PoC tanstack query + tanstack form + toaster in create form page
> (PoC) new questionnaire page

- src/api/questionnaires.ts
- src/constants/dictionary.ts
- src/errors/error.spec.ts
- src/errors/error.ts
- src/layout/loader-error/component.jsx
- src/layout/loader-error/index.jsx
- src/layout/loader-error/loaderError.spec.jsx
- src/layout/page-questionnaire/components/page-questionnaire.jsx
- src/layout/page-questionnaire/containers/page-questionnaire-container.jsx
- src/layout/questionnaire-list-components/components/questionnaire-list-components.jsx
- src/reducers/questionnaire-by-id.jsx
- src/reducers/questionnaire-by-id.spec.jsx
> feat: display not found questionnaire

- src/constants/dictionary.ts
- src/constants/dictionary/declarations.ts
- src/constants/dictionary/loop.ts
- src/constants/dictionary/questionnaire.ts
- src/constants/dictionary/table.ts
- src/constants/dictionary/validation.ts
- Removed some dictionary entries that were not used anymore
- Started to move entries into their own file so that it's a bit more tidy
> refactor: removed unused dictionary entries

- next/package.json
- next/public/silent-sso.htm
- next/src/App.tsx
- next/src/api/utils.ts
- next/src/contexts/oidc.ts
- next/src/hooks/useAuth.ts
- next/src/routes/index.tsx
- next/yarn.lock
Authentication is mandatory, no need to check if user is logged in anymore.
I've let the default error page for now but we should make a fancier one later on.
> build: (next) oidc spa v6 and set authentification as mandatory

- next/package.json
- next/src/api/questionnaires.test.ts
- next/src/api/questionnaires.ts
- next/src/api/stamps.test.ts
- next/src/api/stamps.ts
- next/src/api/utils/codesLists.test.ts
- next/src/api/utils/codesLists.ts
- next/src/api/utils/flowLogic.test.ts
- next/src/api/utils/flowLogic.ts
- next/src/api/utils/formulasLanguage.test.ts
- next/src/api/utils/formulasLanguage.ts
- next/src/api/utils/questionnaires.test.ts
- next/src/api/utils/questionnaires.ts
- next/src/api/utils/targetModes.test.ts
- next/src/api/utils/targetModes.ts
- next/src/contexts/__mocks__/oidc.ts
- next/tests/setup.ts
- next/yarn.lock
Added nock to mock API requests regardless of fetch library used. (No need to mock axios or update tests if we remove axios for example.)
> test: (next) api tests

- src/api/visualize.spec.ts
- src/api/visualize.ts
- src/constants/dictionary.ts
- src/widgets/visualize-dropdown/__snapshots__/visualize-dropdown.spec.tsx.snap
- Complete https://github.com/InseeFr/Pogues/pull/946
Just a few modifications on downloading pogues-model :
- rename the button label in visualization dropdown
- rename the downloaded file name
> chore: rename pogues model download
